name: ML deployment

on : [push]

jobs:
  deploy:
    runs-on : ubuntu-latest
    environment:
      name: docker


    steps:
      - name: Checkout repostery
        uses: actions/checkout@v4

      - name: Set up Pyhton
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Train and evaluate model
        run: python train/train.py
      
      - name: Build Docker image
        run: docker build -t titanic_api .
      
      - name: Login to Docker hub
        run: echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin
      
      - name: Tag Docker Image
        run: docker tag api_tianic ${{ secrets.USERNAME }}/api_titanic

      - name: Push Docker Image
        run : docker push ${{ secrets.USERNAME }}/api_titanic
        
      
