name: ML deployment

on : [push]

jobs:
  deploy:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout repostery
        uses: action/checkout@v4

      - name: Set up Pyhton
        uses: action/setup-python@v4
        with:
          pyhton-version: 3.11.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Train and evaluate model
        run: python train/train.py
        
      
